# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\designer\add_profile_markread.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addProfileDialog(object):
    def setupUi(self, addProfileDialog):
        addProfileDialog.setObjectName("addProfileDialog")
        addProfileDialog.resize(300, 91)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addProfileDialog.sizePolicy().hasHeightForWidth())
        addProfileDialog.setSizePolicy(sizePolicy)
        addProfileDialog.setToolTip("")
        addProfileDialog.setStatusTip("")
        addProfileDialog.setWhatsThis("")
        addProfileDialog.setAccessibleName("")
        addProfileDialog.setAccessibleDescription("")
        self.verticalLayout = QtWidgets.QVBoxLayout(addProfileDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(addProfileDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setAccessibleName("")
        self.label.setAccessibleDescription("")
        self.label.setText("Введите название профиля")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(addProfileDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setToolTip("")
        self.lineEdit.setStatusTip("")
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setAccessibleDescription("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(addProfileDialog)
        self.buttonBox.setToolTip("")
        self.buttonBox.setStatusTip("")
        self.buttonBox.setWhatsThis("")
        self.buttonBox.setAccessibleName("")
        self.buttonBox.setAccessibleDescription("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addProfileDialog)
        self.buttonBox.accepted.connect(addProfileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(addProfileDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addProfileDialog)

    def retranslateUi(self, addProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        addProfileDialog.setWindowTitle(_translate("addProfileDialog", "Добавить профиль"))
        self.lineEdit.setPlaceholderText(_translate("addProfileDialog", "Название профиля..."))
